services:
  kafka:
    image: bitnami/kafka:latest # Use an official Bitnami Kafka image with KRaft support
    container_name: kafka-kraft
    ports:
      - "9092:9092" # Port expose for external communication to docker container
      - "9093:9093" # Internal KRaft communication port
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  kafka-data:
