spring:
  application:
    name: kafka-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-demo-group
    topics:
      happy: kafka-demo-topic-happy
      sad: kafka-demo-topic-sad
      neutral: kafka-demo-topic-neutral
